version: '3'
services:
  postgres-db:
    image: postgres:17.0
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=planning_poker

  spring-boot-app:
      build:
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - postgres-db
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/planning_poker
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres

  react-app:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "3000:80"
