export const QUEUE_PATHS = {
  RECEIVE_MESSAGE: "/user/queue/response",
  USER_MEMBER_UPDATES: "/user/queue/memberUpdates",
};

export const TOPIC_PATHS = {
  SESSION_CREATED: "/topic/session/created",
  SESSION_UPDATES: "/topic/sessionUpdates",
};

export const BACKEND_ACTIONS = {
  CREATE_SESSION: "/app/poker/create",
  JOIN_SESSION: "/app/poker/join",
  LEAVE_SESSION: "/app/poker/leave",
  CLOSE_SESSION: "/app/poker/close",
};

export const FRONTEND_ACTIONS = {
  SESSION_CREATED: "SESSION_CREATED",
  SESSION_CREATION_FAILED: "SESSION_CREATION_FAILED",
  SESSION_JOINED: "SESSION_JOINED",
  SESSION_JOIN_FAILED: "SESSION_JOIN_FAILED",
  SESSION_LEFT: "SESSION_LEFT",
  SESSION_RECONNECTED: "SESSION_RECONNECTED",
  SESSION_RECONNECT_FAILED: "SESSION_RECONNECT_FAILED",
  MEMBER_JOINED: "MEMBER_JOINED",
  MEMBER_LEFT: "MEMBER_LEFT",
};
